export const TREE_TYPES = {
  ADD_TREE: 'TREE_TYPES.ADD_TREE',
  EDIT_TREE: 'TREE_TYPES.EDIT_TREE',
  DELETE_TREE: 'TREE_TYPES.DELETE_TREE',
  GET_TREES:'TREE_TYPES.GET_TREES',
  SET_LOADING:'TREE_TYPES.SET_LOADING'
}